export const appLocale = {
   startsWith: 'Começa com',
   contains: 'Contém',
   notContains: 'Não contém',
   endsWith: 'Termina com',
   equals: 'Igual a',
   notEquals: 'Diferente de',
   noFilter: 'Sem filtro',
   lt: 'Menor que',
   lte: 'Menor ou igual a',
   gt: 'Maior que',
   gte: 'Maior ou igual a',
   dateIs: 'Data é',
   dateIsNot: 'Data não é',
   dateBefore: 'Data antes de',
   dateAfter: 'Data depois de',
   clear: 'Limpar',
   apply: 'Aplicar',
   matchAll: 'Corresponder a todos',
   matchAny: 'Corresponder a qualquer',
   addRule: 'Adicionar regra',
   removeRule: 'Remover regra',
   accept: 'Sim',
   reject: 'Não',
   choose: 'Escolher',
   upload: 'Enviar',
   cancel: 'Cancelar',
   prev: 'Voltar',
   next: 'Avançar',
   selectedItemsLabel: '{0} itens selecionados',
   dayNames: ['Domingo', 'Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado'],
   dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
   dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
   monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
   monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
   chooseYear: 'Escolha o Ano',
   chooseMonth: 'Escolha o Mês',
   chooseDate: 'Escolha a Data',
   prevDecade: 'Década Anterior',
   nextDecade: 'Próxima Década',
   prevYear: 'Ano Anterior',
   nextYear: 'Próximo Ano',
   prevMonth: 'Mês Anterior',
   nextMonth: 'Próximo Mês',
   prevHour: 'Hora Anterior',
   nextHour: 'Próxima Hora',
   prevMinute: 'Minuto Anterior',
   nextMinute: 'Próximo Minuto',
   prevSecond: 'Segundo Anterior',
   nextSecond: 'Próximo Segundo',
   today: 'Hoje',
   weekHeader: 'Sem',
   dateFormat: 'dd/mm/yy'
}